/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppProjetosRouteImport } from './routes/app.projetos'
import { Route as AppProducaoRouteImport } from './routes/app.producao'
import { Route as AppPipelineRouteImport } from './routes/app.pipeline'
import { Route as AppOrcamentosRouteImport } from './routes/app.orcamentos'
import { Route as AppMateriaisRouteImport } from './routes/app.materiais'
import { Route as AppIaProjetosRouteImport } from './routes/app.ia-projetos'
import { Route as AppIaRouteImport } from './routes/app.ia'
import { Route as AppFornecedoresRouteImport } from './routes/app.fornecedores'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppDashboardIaRouteImport } from './routes/app.dashboard-ia'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppCalendarioRouteImport } from './routes/app.calendario'
import { Route as AppBuscaLeadRouteImport } from './routes/app.busca-lead'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosRoute = AppProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AppRoute,
} as any)
const AppProducaoRoute = AppProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosRoute = AppOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppMateriaisRoute = AppMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AppRoute,
} as any)
const AppIaProjetosRoute = AppIaProjetosRouteImport.update({
  id: '/ia-projetos',
  path: '/ia-projetos',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppFornecedoresRoute = AppFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIaRoute = AppDashboardIaRouteImport.update({
  id: '/dashboard-ia',
  path: '/dashboard-ia',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppBuscaLeadRoute = AppBuscaLeadRouteImport.update({
  id: '/busca-lead',
  path: '/busca-lead',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/busca-lead': typeof AppBuscaLeadRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard-ia': typeof AppDashboardIaRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/fornecedores': typeof AppFornecedoresRoute
  '/app/ia': typeof AppIaRoute
  '/app/ia-projetos': typeof AppIaProjetosRoute
  '/app/materiais': typeof AppMateriaisRoute
  '/app/orcamentos': typeof AppOrcamentosRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/producao': typeof AppProducaoRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/busca-lead': typeof AppBuscaLeadRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard-ia': typeof AppDashboardIaRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/fornecedores': typeof AppFornecedoresRoute
  '/app/ia': typeof AppIaRoute
  '/app/ia-projetos': typeof AppIaProjetosRoute
  '/app/materiais': typeof AppMateriaisRoute
  '/app/orcamentos': typeof AppOrcamentosRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/producao': typeof AppProducaoRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/busca-lead': typeof AppBuscaLeadRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard-ia': typeof AppDashboardIaRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/fornecedores': typeof AppFornecedoresRoute
  '/app/ia': typeof AppIaRoute
  '/app/ia-projetos': typeof AppIaProjetosRoute
  '/app/materiais': typeof AppMateriaisRoute
  '/app/orcamentos': typeof AppOrcamentosRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/producao': typeof AppProducaoRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/busca-lead'
    | '/app/calendario'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/dashboard-ia'
    | '/app/financeiro'
    | '/app/fornecedores'
    | '/app/ia'
    | '/app/ia-projetos'
    | '/app/materiais'
    | '/app/orcamentos'
    | '/app/pipeline'
    | '/app/producao'
    | '/app/projetos'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/busca-lead'
    | '/app/calendario'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/dashboard-ia'
    | '/app/financeiro'
    | '/app/fornecedores'
    | '/app/ia'
    | '/app/ia-projetos'
    | '/app/materiais'
    | '/app/orcamentos'
    | '/app/pipeline'
    | '/app/producao'
    | '/app/projetos'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/busca-lead'
    | '/app/calendario'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/dashboard-ia'
    | '/app/financeiro'
    | '/app/fornecedores'
    | '/app/ia'
    | '/app/ia-projetos'
    | '/app/materiais'
    | '/app/orcamentos'
    | '/app/pipeline'
    | '/app/producao'
    | '/app/projetos'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projetos': {
      id: '/app/projetos'
      path: '/projetos'
      fullPath: '/app/projetos'
      preLoaderRoute: typeof AppProjetosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/producao': {
      id: '/app/producao'
      path: '/producao'
      fullPath: '/app/producao'
      preLoaderRoute: typeof AppProducaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pipeline': {
      id: '/app/pipeline'
      path: '/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orcamentos': {
      id: '/app/orcamentos'
      path: '/orcamentos'
      fullPath: '/app/orcamentos'
      preLoaderRoute: typeof AppOrcamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/materiais': {
      id: '/app/materiais'
      path: '/materiais'
      fullPath: '/app/materiais'
      preLoaderRoute: typeof AppMateriaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ia-projetos': {
      id: '/app/ia-projetos'
      path: '/ia-projetos'
      fullPath: '/app/ia-projetos'
      preLoaderRoute: typeof AppIaProjetosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ia': {
      id: '/app/ia'
      path: '/ia'
      fullPath: '/app/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fornecedores': {
      id: '/app/fornecedores'
      path: '/fornecedores'
      fullPath: '/app/fornecedores'
      preLoaderRoute: typeof AppFornecedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard-ia': {
      id: '/app/dashboard-ia'
      path: '/dashboard-ia'
      fullPath: '/app/dashboard-ia'
      preLoaderRoute: typeof AppDashboardIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendario': {
      id: '/app/calendario'
      path: '/calendario'
      fullPath: '/app/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/busca-lead': {
      id: '/app/busca-lead'
      path: '/busca-lead'
      fullPath: '/app/busca-lead'
      preLoaderRoute: typeof AppBuscaLeadRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBuscaLeadRoute: typeof AppBuscaLeadRoute
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppClientesRoute: typeof AppClientesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardIaRoute: typeof AppDashboardIaRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppFornecedoresRoute: typeof AppFornecedoresRoute
  AppIaRoute: typeof AppIaRoute
  AppIaProjetosRoute: typeof AppIaProjetosRoute
  AppMateriaisRoute: typeof AppMateriaisRoute
  AppOrcamentosRoute: typeof AppOrcamentosRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppProducaoRoute: typeof AppProducaoRoute
  AppProjetosRoute: typeof AppProjetosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuscaLeadRoute: AppBuscaLeadRoute,
  AppCalendarioRoute: AppCalendarioRoute,
  AppClientesRoute: AppClientesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardIaRoute: AppDashboardIaRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppFornecedoresRoute: AppFornecedoresRoute,
  AppIaRoute: AppIaRoute,
  AppIaProjetosRoute: AppIaProjetosRoute,
  AppMateriaisRoute: AppMateriaisRoute,
  AppOrcamentosRoute: AppOrcamentosRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppProducaoRoute: AppProducaoRoute,
  AppProjetosRoute: AppProjetosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
